[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "your-package"
version = "0.1.0"
dependencies = []

[project.scripts]
mad = "package.cli:main"

[tool.setuptools]
packages = ["package"]
